allow_anonymous false
password_file /mosquitto/config/password_file
acl_file /mosquitto/config/acl_file

persistence true
persistence_location /mosquitto/data/

log_dest stdout
log_timestamp true
connection_messages true

# MQTT over TLS
listener 8883
certfile /mosquitto/certs/server.crt
keyfile /mosquitto/certs/server.key
tls_version tlsv1.2
require_certificate false